# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-15 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_quotes', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='author_quotes.User'),
        ),
    ]
